### ISSUE TITLE
not an issue - fyi swift + tensorflow + sklearn + python

### ISSUE THREAD

**Issue by johndpope** [ajsnow/Shear#1]
fyi - https://github.com/koher/swift-digits

it's not entirely clear the best way to interact with matrices in swift.
I like your helpers that you've created. 

 I'm wanting to port some python code / and think your matrix helpers are exactly what I need at first glance.
```python

  env_low = env.observation_space.low // Array 
    env_high = env.observation_space.high // Array 
    env_dx = (env_high - env_low) / n_states // divide array of floats by float - return new array

```

```swift

/// Scalar Division
public func /<A: TensorProtocol, X: NumericType>
    (left: A, right: X) -> Tensor<A.Element> where A.Element == X {
        return left.map { $0 / right }
}

/// Left-Scalar Division
public func /<A: TensorProtocol, X: NumericType>
    (left: X, right: A) -> Tensor<A.Element> where A.Element == X {
        return right.map { left / $0 }
}
```

related
https://github.com/tensorflow/swift/issues/70
https://github.com/mattt/Surge/issues/85

https://www.mathworks.com/help/matlab/ref/ldivide.html

**Comment by johndpope** [comment]
I think what I'm wanting is to extend out your helpers to allow more flexibility with arrays.
will give it a crack. seems to be a train wreck of failed attempts on matrix swift projects.
```swift

/// Left-scalar Subtraction
public func -<A: TensorProtocol, X: NumericType>
    (left: X, right: A) -> Tensor<A.Element> where A.Element == X {
        return right.map { left - $0 }
}

// agnostic helper to subtract arrays - allowing  (env_high - env_low)
func - <Element: Hashable>(lhs: [Element], rhs: [Element]) -> [Element]
{
    return Array(Set<Element>(lhs).subtracting(Set<Element>(rhs)))
}

```

**Comment by ajsnow** [comment]
Word of warning: the current (and foreseeable) Shear implementation is hilariously inefficient for any real numeric work. I am fond of the resulting code though 😄
